name: Build And Push
run-name: ${{ gitea.actor }} is runs ci pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: gitea.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            ["git.mausas.de"]          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.mausas.de/maurice.hansen/${{ gitea.repository }}:${{gitea.sha}},git.mausas.de/maurice.hansen/${{ gitea.repository }}:latest"