name: Build And Push
run-name: ${{ gitea.actor }} is runs ci pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    if: gitea.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.mausas.de
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEATOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.custom
          platforms: |
            linux/amd64           
          push: true
          tags: |
            git.mausas.de/${{ gitea.repository }}:latest  