name: Docker Image CI
on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      DOCKER_TAG: :dev
      DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/hassio-whisper
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker Tag for Release
        if: contains(github.ref, 'main')
        run: echo "DOCKER_TAG=:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{env.DOCKER_IMAGE}}${{env.DOCKER_TAG}}

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ${{env.DOCKER_IMAGE}}${{env.DOCKER_TAG}}


